name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pydocstyle pylint black flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        pip install types-setuptools
    - name: mypy
      run: |
        mypy --version
        rm -rf .mypy_cache
        mypy lobsterpy
    - name: pydocstyle
      run: |
        pydocstyle --count lobsterpy
    - name: pylint
      - name: pylint
        run: |
          pylint --version
          pylint --rcfile=pylintrc lobsterpy
    - name: black
      run: |
        black --version
        black --check --diff --color lobsterpy
    - name: flake8
      run: |
        flake8 --version
        flake8 --count --show-source --statistics lobsterpy
        flake8 --count --exit-zero --max-complexity=20 --statistics lobsterpy